### ISSUE TITLE
399158f commit leads to fail. 

### ISSUE THREAD

**Issue by VolodymyrPavliukevych** [vapor/ctls#1]
After latest commit [399158f](https://github.com/vapor/ctls/commit/399158f02b6ccde03d06280414884236dd854520) can't build package.

There is no any ctls.pc file in pkgconfig folder.  You can't install that file throw brew (installing openssl).
Error:    
iMac:CTLS-1.0.0-beta.2 roaming$ swift build
error: only system module package CTLS found
fix: to use this system module package, include it in another project

**Comment by tanner0101** [comment]
This should fix it:

http://stackoverflow.com/questions/43070534/openssl-ctls-trouble-with-vapor-2

**Comment by VolodymyrPavliukevych** [comment]
That is bad way, idea of package module is autoconfig throw pkgcontig system file. If you are building long-chain dependency package all that flags could conflict between themself. In that case we are using pkgconfig files in system modules. 
What is the benefit (goal) of latest commit?

**Comment by VolodymyrPavliukevych** [comment]
Read here https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md pkgConf section.

**Comment by VolodymyrPavliukevych** [comment]
As you can see, travic failed also after that commit.

**Comment by tanner0101** [comment]
There are several issues that led to this method:

1: Homebrew OpenSSL is not linkable even with `--force` (for some security issues). Because of this the `openssl.pc` file cannot be found by SPM.
2: Some users may want to link against their own SSL implementations (such as LibreSSL)
3: MySQL includes non-whitelisted C flags in the `mysqlclient.pc` file. These non-whitelisted flags will abort the SPM build process and cannot be worked around. I assume other packages will share this same fate.

http://stackoverflow.com/questions/38670295/homebrew-refusing-to-link-openssl
https://bugs.swift.org/browse/SR-4195

We're open to alternative solutions if you have any ideas.

**Comment by VolodymyrPavliukevych** [comment]
That way >>https://openssl.vapor.sh is ok. 
But, I think it should be at README file and it's source in the CTLS git (for security reason).
Closed.
Thanks.
